'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, Check, Pause, Play, Copy } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Slider } from '@/components/ui/slider';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { videoSource, type Project } from '@/lib/content';
export function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <div className="field"><label>{label}</label><Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger aria-label={label} className="choice-trigger"><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>}
export function VideoPlayer({url,title,poster,captions}:{url:string;title:string;poster?:string;captions?:string}){const [error,setError]=useState(false);const src=videoSource(url);if(!src)return <p className="notice">No film has been added to this project yet.</p>;return <div className="video-player">{src.kind==='embed'?<><iframe title={title} src={src.url} allow="fullscreen; picture-in-picture; encrypted-media" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/><a className="external-video" href={url} target="_blank" rel="noopener noreferrer">Open on video platform <ArrowUpRight size={14}/></a></>:<><video controls playsInline preload="metadata" poster={poster} onError={()=>setError(true)} aria-label={title}><source src={src.url}/>{captions&&<track kind="captions" src={captions} srcLang="en" label="English" default/>}</video>{error&&<p className="notice">This video couldn’t load. <a href={url} target="_blank" rel="noopener noreferrer">Open the original file</a>.</p>}</>}</div>}
export function Reel({url,projects,open,onOpenChange}:{url:string;projects:Project[];open:boolean;onOpenChange:(v:boolean)=>void}){const [index,setIndex]=useState(0);const [playing,setPlaying]=useState(false);const frames=projects.filter(p=>p.cover);useEffect(()=>{if(!playing||!open||url||!frames.length)return;const timer=setInterval(()=>setIndex(i=>(i+1)%frames.length),2600);return()=>clearInterval(timer)},[playing,open,url,frames.length]);useEffect(()=>{if(!open)setPlaying(false)},[open]);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="reel-dialog"><DialogTitle>{url?'The showreel':'A few possible worlds.'}</DialogTitle><DialogDescription>{url?'A selection of edits, stories, and moments.':'Concept preview • Original AI-created stills. Zohaib’s personal showreel will replace this sequence.'}</DialogDescription>{url?<VideoPlayer url={url} title="Zohaib’s showreel"/>:frames.length?<><div className="demo-reel"><img key={frames[index%frames.length].id} className={playing?'playing':''} src={frames[index%frames.length].cover} alt={frames[index%frames.length].title}/><div className="demo-overlay"><span className="eyebrow">ZOHAIB / CONCEPT SEQUENCE</span><h3>{frames[index%frames.length].title}</h3></div></div><div className="reel-controls"><button className="pill-button" onClick={()=>setPlaying(!playing)}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause sequence':'Play sequence'}</button><div className="reel-dots">{frames.map((p,i)=><button aria-label={`Show ${p.title}`} aria-pressed={i===index%frames.length} key={p.id} onClick={()=>setIndex(i)}/>)}</div><span className="eyebrow">{String(index%frames.length+1).padStart(2,'0')} / {String(frames.length).padStart(2,'0')}</span></div></>:<p>Showreel coming soon.</p>}</DialogContent></Dialog>}
export function ColorCompare({before,after,illustrative=false}:{before:string;after:string;illustrative?:boolean}){const [split,setSplit]=useState(50);return <div className="color-compare"><div className="compare-image"><img src={after} alt="Color look"/><img className={illustrative?'neutral-look':''} src={before} alt={illustrative?'Illustrative muted treatment':'Before color grading'} style={{clipPath:`inset(0 ${100-split}% 0 0)`}}/><div className="compare-divider" style={{left:`${split}%`}}><span>↔</span></div><span className="compare-label before">{illustrative?'MUTED':'BEFORE'}</span><span className="compare-label after">{illustrative?'CINEMATIC':'AFTER'}</span><input type="range" min={0} max={100} value={split} onChange={e=>setSplit(Number(e.target.value))} className="compare-overlay-slider" aria-label="Drag to compare images"/></div><div className="compare-control"><span id="compare-label">Move to compare</span><Slider value={[split]} onValueChange={v=>setSplit(Array.isArray(v)?v[0]:v)} min={0} max={100} aria-label="Color comparison"/><output>{split}%</output></div>{illustrative&&<p className="fine-print">Illustrative color exploration on an AI-created still. The muted look is a simulated treatment.</p>}</div>}
export function InquiryForm({email,open,onOpenChange}:{email:string;open:boolean;onOpenChange:(v:boolean)=>void}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="inquiry-dialog"><DialogTitle>LET’S TALK FILM.</DialogTitle><DialogDescription>Have feedback, a student collaboration, or a story to share? I’d love to hear from you.</DialogDescription><p>This is my personal portfolio and a space to share what I’m learning about editing.</p><a className="primary-button" href={`mailto:${email}?subject=${encodeURIComponent('Hello from your portfolio')}`}>Open email <ArrowUpRight size={18}/></a><CopyEmail email={email}/><a className="underlined-link" href="https://www.instagram.com/zohaib.inmotion/" target="_blank" rel="noopener noreferrer">Find me on Instagram <ArrowUpRight size={16}/></a><p className="fine-print">The email button opens your email app. You can also copy the address and write from your preferred inbox.</p></DialogContent></Dialog>}
export function CopyEmail({email}:{email:string}){const [copied,setCopied]=useState(false);const [error,setError]=useState(false);return <div className="email-row"><a href={`mailto:${email}`}>{email}</a><button aria-label={copied?'Email copied':'Copy email address'} onClick={async()=>{try{await navigator.clipboard.writeText(email);setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{setError(true)}}}>{copied?<Check size={17}/>:<Copy size={17}/>}</button><span role="status" className="copy-status">{copied?'Copied':error?'Select the email to copy it.':''}</span></div>}
