'use client';
import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowDown, ArrowUpRight, Play, Scissors, Film, AudioLines, Palette, Download, Camera, Video } from 'lucide-react';
import { ColorCompare, CopyEmail, InquiryForm, Reel } from './components';
import { categories, type Profile, type Project } from '@/lib/content';
type ModelTool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
export default function Portfolio({profile,projects}:{profile:Profile;projects:Project[]}){
const [filter,setFilter]=useState('All work');const filterRef=useRef(filter);filterRef.current=filter;const [reel,setReel]=useState(false);const [inquiry,setInquiry]=useState(false);const [motion,setMotion]=useState(true);const visible=projects.filter(p=>filter==='All work'||p.category===filter);
useEffect(()=>{document.documentElement.classList.toggle('motion-off',!motion);return()=>document.documentElement.classList.remove('motion-off')},[motion]);
useEffect(()=>{setMotion(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)},[]);
useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(t:ModelTool,o:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;const abort=new AbortController();const tools:ModelTool[]=[{name:'read_portfolio_projects',description:'Read published portfolio projects and the currently selected category.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({category:filterRef.current,projects:projects.filter(p=>filterRef.current==='All work'||p.category===filterRef.current).map(p=>({id:p.id,title:p.title,category:p.category,sample:p.sample,url:`/work/${p.id}`}))})},{name:'filter_portfolio_projects',description:'Change the visible portfolio category. This only changes the work filter; it does not edit saved projects.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['All work',...categories]}},required:['category'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{const value=input as {category?:unknown};if(!value||!['All work',...categories].includes(value.category as string)||Object.keys(value).some(k=>k!=='category'))throw new Error('Choose a valid portfolio category.');flushSync(()=>setFilter(value.category as string));filterRef.current=value.category as string;document.getElementById('work')?.scrollIntoView({behavior:'instant'});return {category:value.category,count:projects.filter(p=>value.category==='All work'||p.category===value.category).length};}}];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:abort.signal})).catch(()=>{})}catch{}}return()=>abort.abort()},[projects]);
return <main className={motion?'motion-on':'motion-off'}>
<header className="site-header"><a className="wordmark" href="/">{profile.name.toUpperCase()}<span>✳</span></a><nav aria-label="Main navigation"><a href="#work">Work <sup>{String(projects.length).padStart(2,'0')}</sup></a><a href="#about">About</a><a href="#process">Process</a><button onClick={()=>setInquiry(true)}>Let’s talk <ArrowUpRight size={16}/></button></nav></header>
<section className="hero"><div className="eyebrow hero-eyebrow"><span><span className="status-dot"/>{profile.tagline.toUpperCase()}</span><span>INDEPENDENT PERSPECTIVE / 2026</span></div><h1 className="hero-title" aria-label="Every frame. A feeling."><span aria-hidden="true">{'EVERY FRAME.'.split('').map((c,i)=><b key={i} style={{animationDelay:`${i*45}ms`}}>{c===' '?' ':c}</b>)}</span><span aria-hidden="true"><b style={{animationDelay:'.15s'}}>A&nbsp;</b><i>{'FEELING.'.split('').map((c,i)=><b key={i} style={{animationDelay:`${i*45+230}ms`}}>{c}</b>)}</i><span className="title-star">✳</span></span></h1><div className="hero-bottom"><p>I’m {profile.name}. I turn raw footage into<br/>stories that stay with you.</p><a href="#work" className="text-link">SCROLL TO EXPLORE <ArrowDown size={17}/></a><button className="reel-button" onClick={()=>setReel(true)}><span className="play-orbit"><Play fill="currentColor" size={17}/></span><span>{profile.showreel?'PLAY SHOWREEL':'PLAY CONCEPT REEL'}<small>{profile.showreel?'A COLLECTION OF MOMENTS':'A PREVIEW OF POSSIBILITIES'}</small></span><ArrowUpRight size={18}/></button></div></section>
<div className="film-strip" aria-label="Project previews">{projects.slice(0,3).map((p,i)=><a href={`/work/${p.id}`} key={p.id}><img src={p.cover} alt={p.title}/><span className="eyebrow">0{i+1} / {p.title.toUpperCase()}</span><ArrowUpRight size={20}/></a>)}<span className="film-strip-edge" aria-hidden="true">24 FPS — A DIFFERENT PERSPECTIVE —</span></div>
<div className="ticker" aria-hidden="true"><div>THE STORY IS IN THE CUT <span>✳</span> EDITING IS A FEELING <span>✳</span> THE STORY IS IN THE CUT <span>✳</span> EDITING IS A FEELING <span>✳</span></div></div>
<section id="work" className="work-section"><div className="section-heading"><div><span className="eyebrow">01 / THE CUTS</span><h2>SELECTED <i>WORK.</i></h2></div><span className="small-note">A few stories.<br/>Different ways to feel.</span></div><div className="work-filters" aria-label="Filter projects">{['All work',...categories.filter(c=>projects.some(p=>p.category===c))].map(c=><button key={c} onClick={()=>setFilter(c)} aria-pressed={filter===c}>{c}<sup>{c==='All work'?projects.length:projects.filter(p=>p.category===c).length}</sup></button>)}<span className="filter-count" aria-live="polite">{String(visible.length).padStart(2,'0')} PROJECTS</span></div><div className="project-grid">{visible.map((p,i)=><a key={p.id} className={`project-card ${i===0?'featured':''}`} href={`/work/${p.id}`}><div className="project-image"><img src={p.cover} alt={p.title} loading="lazy"/>{p.sample&&<span className="sample-badge">SAMPLE CONCEPT</span>}<span className="image-project-title" aria-hidden="true">{p.title}</span><span className="project-arrow"><ArrowUpRight/></span></div><div className="project-caption"><h3><span className="project-index">{String(i+1).padStart(2,'0')}</span>{p.title}</h3><span>{p.category.toUpperCase()} · {p.year}</span></div></a>)}</div>{!visible.length&&<p className="empty-work">No projects in this category yet. Try All work.</p>}{projects.some(p=>p.sample)&&<p className="sample-note">Sample concepts use original AI-created imagery. Personal editing projects coming soon.</p>}</section>
<section className="about-section" id="about"><span className="eyebrow">02 / BEHIND THE TIMELINE</span><div className="about-grid"><h2>A STUDENT.<br/>A STORYTELLER.<br/><i>ALWAYS EDITING.</i></h2><div><Scissors size={40} strokeWidth={1.5}/><p>{profile.bio}</p><div className="about-links">{profile.resume&&<a className="underlined-link" href={profile.resume} target="_blank" rel="noopener noreferrer">View résumé <Download size={17}/></a>}{profile.instagram&&<a aria-label="Instagram" href={profile.instagram} target="_blank" rel="noopener noreferrer"><Camera/></a>}{profile.youtube&&<a aria-label="YouTube" href={profile.youtube} target="_blank" rel="noopener noreferrer"><Video/></a>}</div><div className="availability"><span className="status-dot"/>{profile.available?'Exploring film, editing & student collaborations':'Currently focused on ongoing projects'}</div></div></div></section>
<section className="look-section"><div className="look-copy"><span className="eyebrow">03 / A DIFFERENT MOOD</span><h2>SAME FRAME.<br/><i>NEW FEELING.</i></h2><p>Color changes the way a story feels. Slide between two looks and see the difference for yourself.</p><div className="look-note"><Palette size={18}/><span>THE ART IS IN THE DETAILS</span></div></div><ColorCompare before="/images/desert-road.png" after="/images/desert-road.png" illustrative/></section>
<section id="process" className="process-section"><div className="section-heading"><div><span className="eyebrow">04 / FROM RAW TO REAL</span><h2>GOOD STORIES.<br/><i>THOUGHTFUL CUTS.</i></h2></div><p className="process-intro">A clear process, with room<br/>for the unexpected.</p></div><div className="process-grid">{[{icon:Film,n:'01',title:'Find the story',text:'Start with an idea, audience, references, and the footage. Decide what the audience should feel.'},{icon:Scissors,n:'02',title:'Build the rhythm',text:'Shape the first cut. Find the pace, the structure, and the moments that deserve to breathe.'},{icon:AudioLines,n:'03',title:'Make it feel',text:'Bring color, sound, and motion together. Refine the edit through reflection and feedback.'},{icon:ArrowUpRight,n:'04',title:'Make the final cut',text:'Review the details, prepare the right formats, and get the story ready for its audience.'}].map(p=><article key={p.n}><div><p.icon size={29} strokeWidth={1.4}/><span className="eyebrow">{p.n}</span></div><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></section>
<footer id="contact" className="contact-footer"><div className="contact-top"><span className="eyebrow">HAVE A STORY IN MIND?</span><span className="eyebrow">LET’S FIND ITS RHYTHM.</span></div><button className="contact-title" onClick={()=>setInquiry(true)}>LET’S MAKE<br/><i>THE CUT.</i><ArrowUpRight/></button><div className="contact-action"><CopyEmail email={profile.email}/><button className="outline-button" onClick={()=>setInquiry(true)}>Say hello <ArrowUpRight size={18}/></button></div><div className="footer-bottom"><span>© 2026 {profile.name.toUpperCase()} / MADE WITH INTENTION.</span><div><button onClick={()=>setMotion(!motion)} aria-pressed={motion}>Motion {motion?'on':'off'}</button><a href="https://www.instagram.com/zohaib.inmotion/" target="_blank" rel="noopener noreferrer">Instagram <ArrowUpRight size={13}/></a><a href="#main-content" aria-label="Back to top">BACK TO TOP ↑</a></div></div></footer>
<Reel url={profile.showreel} projects={projects} open={reel} onOpenChange={setReel}/><InquiryForm email={profile.email} open={inquiry} onOpenChange={setInquiry}/>
</main>}
