export const categories = ['Short film','Social edit','Music','Motion design'] as const;
export type Project = { id:string; title:string; category:string; year:string; duration:string; role:string; summary:string; approach:string; credits:string; cover:string; video:string; captions:string; before:string; after:string; sample:boolean; published:boolean; position:number };
export type Profile = { name:string; tagline:string; bio:string; email:string; showreel:string; resume:string; instagram:string; youtube:string; available:boolean };
export type Inquiry = { id:string; name:string; email:string; type:string; budget:string; deadline:string; message:string; status:string; createdAt:number };
export const defaultProfile:Profile = { name:'Zohaib',tagline:'Media student & video editor',bio:'I’m Zohaib, a media student exploring how editing, color, and sound turn a collection of shots into a story. I’m interested in the details: a pause, a perfectly timed cut, and the feeling a film leaves behind.',email:'zohaibabid845@gmail.com',showreel:'',resume:'',instagram:'https://www.instagram.com/zohaib.inmotion/',youtube:'',available:true };
export const sampleProjects:Project[] = [
{id:'somewhere-still',title:'Somewhere, Still.',category:'Short film',year:'2026',duration:'Concept study',role:'Edit direction · Color exploration',summary:'A quiet road. An open horizon. A story told in the space between moments.',approach:'An illustrative short-film direction built around patient pacing, warm highlights, and a sense of distance. This sample imagines how a journey could unfold through restrained cuts and an atmospheric sound bed.',credits:'Fictional sample concept. Original AI-created still imagery; not a completed film or a client commission.',cover:'/images/desert-road.png',video:'',captions:'',before:'',after:'',sample:true,published:true,position:0},
{id:'after-hours',title:'After Hours',category:'Social edit',year:'2026',duration:'Concept study',role:'Edit direction · Visual rhythm',summary:'The city slows down. The details get louder.',approach:'A sample social-film direction contrasting red light with cool reflections. The intended edit moves between wide establishing moments and quick details, using the rhythm of the city to guide the cuts.',credits:'Fictional sample concept. Original AI-created still imagery; not a completed film or a client commission.',cover:'/images/rainy-city.png',video:'',captions:'',before:'',after:'',sample:true,published:true,position:1},
{id:'feel-the-frequency',title:'Feel the Frequency',category:'Music',year:'2026',duration:'Concept study',role:'Edit direction · Performance',summary:'That split second when a room becomes a feeling.',approach:'An illustrative music-film direction focused on silhouettes, negative space, and performance energy. A starting point for exploring how sustained frames and faster cuts can follow the emotional shape of a track.',credits:'Fictional sample concept. Original AI-created still imagery; not a completed film or a client commission.',cover:'/images/live-performance.png',video:'',captions:'',before:'',after:'',sample:true,published:true,position:2}
];
export function videoSource(value:string):{kind:'embed'|'video';url:string}|null {
  if(!value)return null;
  if(/^\/api\/media\/[a-zA-Z0-9.-]+$/.test(value))return {kind:'video',url:value};
  try { const u=new URL(value); if(u.protocol!=='https:')return null;
    if(['youtube.com','www.youtube.com','m.youtube.com','youtu.be'].includes(u.hostname)){const id=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.match(/^\/(?:shorts|embed)\/([\w-]+)/)?.[1];return id&&/^[\w-]{11}$/.test(id)?{kind:'embed',url:`https://www.youtube-nocookie.com/embed/${id}`}:null;}
    if(['vimeo.com','www.vimeo.com','player.vimeo.com'].includes(u.hostname)){const id=u.pathname.match(/(?:video\/)?(\d+)/)?.[1];const hash=u.searchParams.get('h')||u.pathname.match(/\d+\/([a-f0-9]+)/)?.[1];return id?{kind:'embed',url:`https://player.vimeo.com/video/${id}${hash?'?h='+encodeURIComponent(hash):''}`}:null;}
    return /\.(mp4|webm|mov)$/i.test(u.pathname)?{kind:'video',url:value}:null;
  }catch{return null;}
}
